name: Pre-receive

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: yarn install
      - run: yarn node .github/workflows/pre-receive.js
